server:
  port: 8080
  servlet:
    context-path: /bank

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bankboot
    username: root
    password: 1310
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



